# Data extracts for occupancy models
This code extracts the species presence/absence and covariatates data from the SQL database and rearranges it into the correct format for the occupancy models. These are then run using R/Jags.

In [1]:
import pandas as pd
import numpy as np
import datetime
from sqlalchemy import create_engine
from rpy2.robjects import pandas2ri, r
pandas2ri.activate()

Here we select the required data - at the moment working with a very small subset (hummingbirds, Colorado, 2008-2014) while testing out code. 

In [5]:
# connect to database
engine = create_engine('postgresql://postgres:password123.@localhost:5432/ebird_us_data')

# Extract the data for US, humminbirds, from 2004-2014
humdat = pd.read_sql_query("""SELECT info.sampling_event_id, 
                           loc_id, 
                           latitude, 
                           longitude, 
                           year, 
                           month, 
                           day, 
                           time,
                           effort_hrs,
                           number_observers,
                           pop00_sqmi,
                           housing_density,
                           sppres.species
                           FROM ebird_checklist_info info
                           INNER JOIN ebird_checklist_species sppres
                               ON info.sampling_event_id = sppres.sampling_event_id
                           INNER JOIN ebird_species_info spinfo
                               ON sppres.species = spinfo.species
                           WHERE family = 'Trochilidae' 
                           AND year >=2004
                           AND month IN (5, 6, 7) 
                           AND count_type IN ('P21', 'P22', 'P34')"""
                           , con=engine)

# check the data
humdat.shape

ImportError: No module named 'psycopg2'

Convert the observation date to full date and give a value of 1 to each observation (will be used later).

In [29]:
humdat['obs_date'] = humdat.apply(lambda x: datetime.datetime.strptime(str(x['year']) + ' ' + str(x['day']), '%Y %j').strftime('%Y-%m-%d'), axis = 1)
humdat['value'] = 1

So here I'm reducing the data so that I only have month/location combinations with >= 3 replicates (equal to the lowest threshold used by Kamp et al. 2016) and then taking all locations where at least 5 years have +3 observations. This is subject to change after discussions because the choices are essentially arbitrary. 

In [30]:
humdat_sml = humdat[['obs_date', 'year', 'loc_id']].drop_duplicates().groupby(['loc_id', 'year']).size().reset_index()
humdat_sml.columns = ['loc_id', 'year', 'obs']
humdat_month_location = humdat_sml.pivot(index = 'loc_id', columns = 'year', values = 'obs').fillna(value=0)
humdat_location_obs = humdat_month_location.apply(lambda x: (x >= 3).sum(), axis = 1)
humdat_location = humdat_location_obs[humdat_location_obs >= 3].reset_index()
humdat_obs = humdat[humdat.loc_id.isin(humdat_location.loc_id)]

Number of locations

In [31]:
humdat_location.shape[0]

263

Number of observations

In [32]:
humdat_obs.shape[0]

38354

Output the locations before and after data pruning to plot for comparison in r


In [33]:
locations_sml = humdat_obs[['loc_id', 'latitude', 'longitude']].drop_duplicates()
locations_full = humdat[['loc_id', 'latitude', 'longitude']].drop_duplicates()
r_locations_sml = pandas2ri.py2ri(locations_sml)
r.assign("locations_sml", r_locations_sml)
r("save(locations_sml, file='D:/eBird_trends/locations_sml.rda')")
r_locations_full = pandas2ri.py2ri(locations_full)
r.assign("locations_full", r_locations_full)
r("save(locations_full, file='D:/eBird_trends/locations_full.rda')")

rpy2.rinterface.NULL

Now we need to get the values of the covariates for each of the replicates. Covariates are:

- time 
- effort (hrs)
- day
- year
- population per square mile
- housing density (sq mile)
- number of observers 

(NB. replicates are being reduced down to one replicate per day, so we will be taking the earliest time and a sum of the effort and number of observers)

In [40]:
covariate_dat = humdat_obs.groupby(['loc_id', 'obs_date']).agg({'time': np.min, 'effort_hrs': np.sum, 'day': np.mean, 'year': np.mean, 'pop00_sqmi': np.mean, 'housing_density': np.mean, 'number_observers': np.sum}).reset_index()

In [52]:
covariate_dat.shape

(11107, 9)

Get information for input to the function - maximum number of replicates; unique locations, years and species.

In [158]:
# get the maximum number of unique sampling replicates 
max_rep = humdat_obs[['obs_date', 'year', 'loc_id']].drop_duplicates().sort_values(['loc_id', 'obs_date'])
max_rep = max(max_rep.groupby(['loc_id', 'year']).size())
year = np.sort(humdat_obs.year.unique())
loc_id = humdat_obs.loc_id.unique()
species = pd.DataFrame(humdat_obs.species.unique(), columns = ['species'])
species_full = pd.DataFrame(humdat.species.unique(), columns = ['species'])
year

array([2008, 2009, 2010, 2011, 2012, 2013, 2014], dtype=int64)

Species lost by filtering the data:

In [18]:
missing_species = species_full[~species_full.species.isin(species.species)]
missing_species

species
8  Eugenes_fulgens

Next we define a function to get the species presence absence data into the correct order, set up a year x location x species x replicate array for input to the occupancy model and then loop through years and locations to create it. 

In [143]:
def data_juggle(in_dat, cov_dat, timestep, location, species, max_rep):
    dat_sub = in_dat[(in_dat.year == timestep) & (in_dat.loc_id == location)]
    dat_sub = dat_sub[['species', 'obs_date', 'value']].drop_duplicates()
    cov_sub = cov_dat[(cov_dat.year == timestep) & (cov_dat.loc_id == location)]
    cov_sub = cov_sub[['obs_date', 'time', 'number_observers', 'effort_hrs']].drop_duplicates()
    
    # get lookup for date/time and replicate
    if dat_sub.shape[0]==0:
        out_dat = np.zeros((species.size, max_rep))
        out_dat[:] = np.NaN
        time = np.zeros((max_rep))
        time[:] = np.NaN
        number_observers = np.zeros((max_rep))
        number_observers[:] = np.NaN
        effort_hrs = np.zeros((max_rep))
        effort_hrs[:] = np.NaN
        
    else:
        sampling_reps = dat_sub[['obs_date']].drop_duplicates().sort_values(['obs_date'])
        sampling_reps['replicate'] = range(1, len(sampling_reps) + 1)
        
        dat_samp_reps = dat_sub.merge(sampling_reps)
        dat_wide = dat_samp_reps.pivot(index = 'species',columns = 'replicate', values = 'value').reset_index()
        dat_species = species.merge(dat_wide,how = "left").fillna(value = 0)
        extra_cols = list(range(dat_species.columns[dat_species.shape[1]-1]+1, max_rep+1))
        extra_cols = pd.DataFrame(index = dat_species.index, columns = extra_cols)
        out_dat = pd.concat([dat_species, extra_cols], axis = 1).drop(['species'], axis = 1).as_matrix()
        print(str(timestep) + ' ' + str(location) + ' done...')
        
        cov_samp_reps = cov_sub.merge(sampling_reps)
        extra_reps = np.zeros((max_rep - cov_sub.shape[0]))
        extra_reps[:] = np.NaN
        time = cov_samp_reps.time.values
        time = np.concatenate([time, extra_reps])
        number_observers = cov_samp_reps.number_observers.values
        number_observers = np.concatenate([number_observers, extra_reps])
        effort_hrs = cov_samp_reps.effort_hrs.values
        effort_hrs = np.concatenate([effort_hrs, extra_reps])
    dat_list = list([out_dat, time, number_observers, effort_hrs])
    return dat_list;

In [159]:
# obs data and covariates that are location/replicate specific and need to go through loop
wide_dat = np.zeros((year.size, loc_id.size, species.size, max_rep))
time = np.zeros((year.size, loc_id.size, max_rep))
number_observers = np.zeros((year.size, loc_id.size, max_rep))
effort_hrs = np.zeros((year.size, loc_id.size, max_rep))

for i in range(0, len(year)):
    for j in range(0, len(loc_id)):
        dat_covs = data_juggle(humdat_obs, covariate_dat, year[i], loc_id[j], species, max_rep)
        wide_dat[i][j] = dat_covs[0]
        time[i][j] = dat_covs[1]
        number_observers[i][j] = dat_covs[2]
        effort_hrs[i][j] = dat_covs[3]
        
# other covariates
day = np.r_[1:max_rep+1] # currently it's set just to the same as the rep number - might need change?
covariate_loc = covariate_dat[['loc_id', 'pop00_sqmi', 'housing_density']].drop_duplicates().sort_values(['loc_id'])
pop00_sqmi = covariate_loc.pop00_sqmi.values
housing_density = covariate_loc.housing_density.values

2008 L109300 done...
2008 L335643 done...
2008 L168263 done...
2008 L109301 done...
2008 L338197 done...
2008 L386990 done...
2008 L360320 done...
2008 L109291 done...
2008 L131621 done...
2008 L285737 done...
2008 L208660 done...
2008 L233493 done...
2008 L140460 done...
2008 L131388 done...
2008 L109292 done...
2008 L292404 done...
2008 L610738 done...
2008 L568294 done...
2008 L213905 done...
2008 L109237 done...
2008 L182188 done...
2008 L798588 done...
2008 L804048 done...
2008 L804049 done...
2008 L804033 done...
2008 L804036 done...
2008 L268316 done...
2008 L804034 done...
2008 L234385 done...
2008 L140473 done...
2008 L1743685 done...
2008 L356579 done...
2008 L211246 done...
2008 L580168 done...
2008 L140459 done...
2008 L167924 done...
2008 L298785 done...
2008 L304178 done...
2008 L304177 done...
2008 L109289 done...
2008 L153890 done...
2008 L384546 done...
2008 L332319 done...
2008 L124261 done...
2008 L580325 done...
2008 L190798 done...
2008 L233562 done...
2008 L342269

In [160]:
r.assign("wide_dat", wide_dat)
r.assign("time", time)
r.assign("number_observers", number_observers)
r.assign("effort_hrs", effort_hrs)
r.assign("day", day)
r.assign("pop00_sqmi", pop00_sqmi)
r.assign("housing_density", housing_density)
r("all_dat = list(sp_obs = wide_dat, time = time, number_observers = number_observers, effort_hrs = effort_hrs, day = day, pop00_sqmi = pop00_sqmi, housing_density = housing_density)")
r("save(all_dat, file='D:/eBird_trends/data/hummingbirds_colorado.rda')")

rpy2.rinterface.NULL

In [4]:
r("memory.limit()")

array([ 98271.])

In [3]:
r("memory.limit(98271)")

array([ 98271.])